<?php

$title = 'Edit user';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'user',
    array(
        'action' => 'edit',
        'id' => $this->id,
    )
));

$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('firstName'));
echo $this->formRow($form->get('lastName'));
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('birthYear'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();