<?php
$title = 'Users';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('user', array('action'=>'add'));?>">Add new user</a>
</p>

<table class="table">
    <tr>
        <th>Name</th>
        <th>Email</th>
        <th>&nbsp;</th>
    </tr>

    <?sphp
    /**
     * @var \User\Model\User $user
     */
    ?>
    <?php foreach ($users as $user) : ?>
        <tr>

            <td><?php echo $this->escapeHtml($user->getFirstName().' '.$user->getLastName());?></td>
            <td><?php echo $this->escapeHtml($user->getEmail());?></td>
            <td>
                <a href="<?php echo $this->url('user',
                    array('action'=>'edit', 'id' => $user->getId()));?>">Edit</a>
                <a href="<?php echo $this->url('user',
                    array('action'=>'delete', 'id' => $user->getId()));?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>